version: '3.9'

services:
  mongo:
    image: mongo:7.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=postgres
      - MONGO_INITDB_ROOT_PASSWORD=postgres
      - MONGO_INITDB_DATABASE=traning
      - MONGO_INITDB_USERNAME=traning
      - MONGO_INITDB_PASSWORD=12345678
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./data/mongo:/data/db
    networks:
      - btr-network

  app:
    build: .
    ports:
      - 5001:5000
    networks:
      - btr-network

networks:
    btr-network:
      name: btr-network
      